Fix compilation error for unreported exceptions
In Java 1.6 source mode, javac reported the error:

```
src/main/java/org/libvirt/Library.java:93: unreported exception java.lang.Exception; must be caught or declared to be thrown
```

Since the code inside the try block does not throw any checked
exceptions, we only need to handle unchecked exceptions on the catch
side, ie. RuntimeExceptions.